---
- hosts: localhost
  tasks:
    - name: Install basic packages (neovim, ag)
      apt:
        name: "{{ packages }}"
        update_cache: yes
      become: yes
      vars:
        packages:
          - neovim
          - curl
          - fonts-hack-ttf
          - tmux
          - silversearcher-ag
          - cmake
          - python-dev
          - python3-dev
          # - fzf


    - name: Install vim plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload/plug.vim
      tags:
        - vim

    - name: Copy common .vimrc
      copy:
        src: files/.vimrc
        dest: ~/.vimrc
      tags:
        - vim

    - name: Copy common .gvimrc
      copy:
        src: files/.gvimrc
        dest: ~/.gvimrc
      tags:
        - vim

    - name: Create required directories
      file:
        path: "~/.vim/{{ paths }}"
        state: directory
      vars:
        paths:
          - backup/
          - undo/
      tags:
        - vim

    - name: Copy nvim config
      copy:
        src: files/init.vim
        dest: ~/.config/vim/
      tags:
        - vim

    - name: Install nvim plugins
      shell: nvim +'PlugInstall --sync' +'PlugUpdate' +qa --headless
      tags:
        - vim


    - name: Copy ssh_config
      copy:
        src: files/.ssh_config
        dest: ~/.ssh/config
      tags:
        - ssh


    - name: Copy gitconfig
      copy:
        src: files/.gitconfig
        dest: ~/.gitconfig


    - name: Install tmux package manager (TPM)
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: ~/.tmux/plugins/tpm
      tags:
        - tmux

    - name: Install .tmux.conf
      copy:
        src: files/.tmux.conf
        dest: ~/.tmux.conf
      tags:
        - tmux

    - name: Install tmuxline
      copy:
        src: files/.tmuxline
        dest: ~/.tmuxline
      tags:
        - tmux


    - name: Install rust
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -yyy
      args:
        creates: ~/.cargo/bin/cargo


    - name: Set up todo
      copy:
        content: ""
        dest: "~/.todo/{{ files }}"
        force: no
      vars:
        files:
          - todo.txt
          - done.txt


    - name: Set up .bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          export BAT_THEME="OneHalfDark"

          alias gl="git lg"
          alias tmux="tmux -2"

          alias vim="nvim"
          export EDITOR="nvim"

          # Todo
          export TODOTXT_DEFAULT_ACTION=ls
          alias t="todo.sh"
          complete -F _todo t

